name: dictionaries
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_fancy_tree_view: ^1.6.0
  json2yaml: ^3.0.1
  localpkg:
    git:
      url: https://github.com/Calebh101/localpkg-flutter-2.git
      ref: main

  mahop_data_table: ^1.0.6
  menu_bar: ^0.5.3
  plist_parser: ^0.2.5
  styled_logger: ^1.0.2
  xml: ^6.6.1
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
