name: dictionaries
description: "Dictionaries"
publish_to: 'none'
version: 0.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  localpkg_flutter:
    git:
      url: https://github.com/Calebh101/localpkg-flutter-2.git
      ref: f571d1665760fcc2fadab376f56b4b4e12ca2f1a

  file_picker: ^10.3.3
  file_saver: ^0.3.1
  flutter_environments_plus: ^1.0.1
  flutter_fancy_tree_view: ^1.6.0
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  intl: ^0.20.2
  json2yaml: ^3.0.1
  linked_scroll_controller: ^0.2.0
  mahop_data_table: ^1.0.6
  menu_bar: ^0.5.3
  plist_parser: ^0.2.5
  shared_preferences: ^2.5.3
  styled_logger: ^1.0.2
  tab_indicator_styler: ^2.0.0
  uuid: ^4.5.1
  xml: ^6.6.1
  yaml: ^3.1.3
  collection: ^1.19.1
  bson: ^5.0.7
  web: ^1.1.1
  meta: ^1.16.0
  any_date: ^1.2.1
  flutter_context_menu: ^0.3.0
  undo: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#151018"
  image: assets/splash.png
  fullscreen: true

# Generate splash screens: dart run flutter_native_splash:create
# Make splash icon from web favicon: convert web/favicon.png -resize 512x512 assets/splash.png
